services:
  cache-server:
    build:
      dockerfile: ./cache-server/Dockerfile
      context: .
    restart: unless-stopped
    deploy:
      replicas: 10
      resources:
        limits:
          memory: 256M
    networks:
      - network
    environment:
      - ZK_CONNECT=zookeeper:2181

  sample:
    build:
      dockerfile: ./sample/Dockerfile
      context: .
    depends_on:
      - cache-server
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 256M
    networks:
      - network
    environment:
      - ZK_CONNECT=zookeeper:2181

  zookeeper:
    image: zookeeper
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - network
    ports:
      - name: zk
        published: 2181
        target: 2181
        protocol: tcp
    environment:
      - ZOO_SERVERS=server.1=zookeeper:2888:3888;2181
    volumes:
      - type: bind
        source: ./.zookeeper
        target: /data
      - type: tmpfs
        target: /datalog
      - type: tmpfs
        target: /logs

  zoonavigator:
    image: elkozmon/zoonavigator
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 384M
    networks:
      - network
    ports:
      - name: web
        published: 9000
        target: 9000
        protocol: tcp
        app_protocol: http
    environment:
      - HTTP_PORT=9000
      - CONNECTION_ZK_NAME=zookeeper
      - CONNECTION_ZK_CONN=zookeeper:2181

networks:
  network:
    name: network